### ISSUE TITLE
We Need a Sweet Domain Name

### ISSUE THREAD

**Issue by Miserlou** [data-refinery/data-refinery#105]
Eventually, we're going to need a domain name for our production deployment. Since `.bio` recently opened, we should think about getting something good before they all get scooped. For example, `refine.bio` is available, as is `harmony.bio`.

Related to naming discussion in #103.

Also pinging @dvenprasad and @jaclyn-taroni .

**Comment by dvenprasad** [comment]
I like refine.bio.
data.bio? Too broad?

**Comment by cgreene** [comment]
nobody likes `refine.ccdatalab.org` to help with branding?

BTW, it may be worth considering migrating this repo to the @AlexsLemonade account before we launch. We initially were using this one because @ctb and @ckingsford's groups were considering partnering on this effort. However, at this point I think it's probably safe to assume we're largely on our own. We probably should start to think about building our brand.

**Comment by kurtwheeler** [comment]
`refine.bio` could be really nice to have, as would `ccdatalab.bio`. We could have `refine.bio` redirect to `refine.ccdatalab.bio` if we wanted... however we should note that `*.bio` domain names are ~60 bucks a year. That might be cheap as far as branding expenses go though... I'm not super opinionated though, just throwing out ideas.

**Comment by cgreene** [comment]
Can someone bring this up in ALSF slack and tag @lemonadejay? He may have input. Also - see my comment above about migrating to an Alex's org. Easier now than later.

**Comment by kurtwheeler** [comment]
I think you're definitely correct about moving this to the Alex's org. I'll see if I have the correct permissions to make that happen. I'll pop this into the ALSF slack.

**Comment by dhimmel** [comment]
`refine.bio` and `data.bio` are both A+. `refine.ccdatalab.bio`... not so much.

**Comment by Miserlou** [comment]
Related to this:

Both [IBM](https://www.ibm.com/cloud/data-refinery) and [Hitatchi](http://www.pentaho.com/streamlined-data-refinery) already have commercial cloud products called "Data Refinery", which completely dominate the first two pages of Google search results. (We currently rank on page three with the CCDL web page for the term Data Refinery, and I can't find the GitHub page anywhere.) Furthermore, there is a more popular AI/Machine Learning project on GitHub called the [Data Refinery](https://github.com/BBVA/data-refinery), which also has the [PyPI package](https://pypi.python.org/pypi/data-refinery) registered and published. It's a really crowded term.

So, I thought maybe we could go with "BioRefinery", but turns out that's already an entire [industry](https://en.wikipedia.org/wiki/Biorefinery) devoted to the production of biofuel. ¯\_(ツ)_/¯

I still like Harmony as a project name but would love to hear some other ideas here.

**Comment by Miserlou** [comment]
I coined the term "Metasequence" which I quite like, Deepa used out the word "Uniform" which I also like.

**Comment by cgreene** [comment]
Uhh, `metasequence` is going to be a bit confusing with the metagenomics field so we may need to avoid that one. Uniform is nice. It's too bad romania is Ro instead of a Rm suffix! `uniform.bio` is available.
