### ISSUE TITLE
Run postgres within a container during development

### ISSUE THREAD

**Issue by kurtwheeler** [data-refinery/data-refinery#66]
I originally chose not to do this because I wanted to match production more closely, but I have since been convinced that the difference isn't really meaningful. The benefits to this are that new developers will have an easier time getting up and running with the Data Refinery. It also will be a good intro project for @dongbohu

**Comment by Miserlou** [comment]
I've got this working locally, will send a PR to `-dev` once we get our git branch workflow set up.

**Comment by Miserlou** [comment]
PR sent: https://github.com/data-refinery/data-refinery/pull/99
